### ISSUE TITLE
Node-RED 2.0 Discussion

### ISSUE THREAD

**Issue by knolleary** [node-red/designs#47]
Node-RED 2.0 is scheduled for the end of April 2021, to coincide with the end of life for Node 10.x

That is just 8 weeks to go. That is not a lot of time to do any significant development work given the current available resources. There are some items we know we need to do, and there are some changes we'd like to make to take advantage of the major-version change.

This issue is a place-holder to gather requirements for 2.0.

We'll plan and track the work on [this project board](https://github.com/orgs/node-red/projects/8).

If there is an item you think we should consider for 2.0, please add a comment to this issue and we can discuss.

**Comment by dceejay** [comment]
Other items I'd like to consider for 2.0 are

- [ ] Add jsonata support for [spacetime module](https://www.npmjs.com/package/spacetime) rather than moment (and deprecate that over time) - much smaller and currently well maintained.
- [ ] Consider moving rbe and tail node either into core or out totally (or maybe rbe in and tail out) - so that people who want to just embed Node-RED can do so with a clean palette - (ref @hardillb )
- [ ] Remove httpRoot option from settings.js as it is overlapping with other options.
- [ ] Make debug sidebar default to "this flow only" (or make sticky to user/editor session) - as folk are now using larger flows, other messages get more and more distracting.
- [ ] Remove msg. option from inject node options (on right) - as there is no incoming msg to an inject node.
- [ ] Make Delay node flush option consistent - (in one mode it flushes then sends new message - in another it just flushes.)

Also maybe
- [ ] File node (and maybe others) - change default directory to be system/users directory rather than .node-red ?
- [ ] Consider blocking file access to certain folders (like .node-red) by default ( so can't just read creds - write over files by mistake etc)

**Comment by knolleary** [comment]
They all sound reasonable for consideration.

Re changing the default directory, we do have [this item](https://trello.com/c/J94q5HuS) on the backlog which will cover this I think.

**Comment by dceejay** [comment]
re RBE - yes totally up for a rebrand - it's 100% obvious to those who know what it is and 100% non-obvious to anyone who doesn't  - Filter does sound a bit wide ranging though - though of course the node itself could also change.

re httpRoot - yes re deprecation - I think it does/can cause confusion especially when it comes to setting up authentication.

**Comment by knolleary** [comment]
I have added all of those items (plus a couple others) to the project plan.

**Comment by dceejay** [comment]
Do we need to list all the other libs that would get upgraded eg socket.io ? or is that BAU ?

**Comment by knolleary** [comment]
BAU unless there are major version bumps we've been holding back. Can't think what's in that list off the top of my head, but yes, worth checking.

**Comment by knolleary** [comment]
Just realised I've created the Project in the wrong place - it should be at the org level, not under the node-red repo. Sigh. Will migrate over and update links here.

**Comment by knolleary** [comment]
New link - https://github.com/orgs/node-red/projects/8

**Comment by echoix** [comment]
I think it could be useful to consider integrating some translation software like Transifex, Crowdin or other online tool if Node-RED is being serious about localizing the editor and popular nodes. I saw a lot of work for the German translation recently, but if the workflow is to be stable enough to apply to other languages, I think it could be a win. For my part, I started contributing to open-source software with translation fixes before being confident enough to create PRs. Tools like these are useful with translation memory, and help review contributions by voting the suggested changes, and most are glad to help open-source software.

I'd be glad to help with French (Canada) translation if it was easier to start.

**Comment by hardillb** [comment]
Something for the list,
A way to secure a catalogue URL. At the moment if you try and include a username/password in the URL in settings.js the browser strips them out. e.g. https://foo:bar@catalogue.example.com/catalogue.json

This is because the catalogue URL needs to be accessible from the browser running the editor.

The rational is to try and reduce the data exposure for supply chain attacks. At the moment I'm mitigating by the fact that the private catalogue only includes packages that are scoped to a prefix that npm is setup to only pull from a private repo that is only available inside the hosting environment

**Comment by dceejay** [comment]
And also - run accessability checker on latest editor and ensure some basic level of compliance.

**Comment by knolleary** [comment]
Closing as 2.0 has sailed
